"""Frozen policy vocabulary and typed failures for W03-C06."""

from __future__ import annotations

from typing import Final

HUMAN_DECISION_POLICY_VERSION: Final = "w03-c06-human-v1"
HUMAN_DECISION_STORE_VERSION: Final = "w03-c06-store-v1"
HUMAN_DECISION_WORKFLOW_VERSION: Final = "w03-c06-workflow-v1"
HUMAN_DECISION_PRODUCER: Final = "flowlens.decision.c06_human"

C06_NONCANONICAL_C05_PACKET: Final = "C06_NONCANONICAL_C05_PACKET"
C06_PACKET_BINDING_MISMATCH: Final = "C06_PACKET_BINDING_MISMATCH"
C06_DECISION_TIME_BEFORE_RUN: Final = "C06_DECISION_TIME_BEFORE_RUN"
C06_REASON_CODE_UNKNOWN: Final = "C06_REASON_CODE_UNKNOWN"
C06_REASON_CODE_OVERLAP: Final = "C06_REASON_CODE_OVERLAP"
C06_PREVIOUS_EVENT_MISMATCH: Final = "C06_PREVIOUS_EVENT_MISMATCH"
C06_CHAIN_RUN_MISMATCH: Final = "C06_CHAIN_RUN_MISMATCH"
C06_CHAIN_PACKET_MISMATCH: Final = "C06_CHAIN_PACKET_MISMATCH"
C06_CHAIN_TIME_REGRESSION: Final = "C06_CHAIN_TIME_REGRESSION"
C06_STORE_ROOT_INVALID: Final = "C06_STORE_ROOT_INVALID"
C06_STORE_BUSY: Final = "C06_STORE_BUSY"
C06_STORE_DIRTY: Final = "C06_STORE_DIRTY"
C06_STORE_CORRUPT: Final = "C06_STORE_CORRUPT"
C06_STORE_FORK: Final = "C06_STORE_FORK"
C06_STORE_CYCLE: Final = "C06_STORE_CYCLE"
C06_EVENT_ID_COLLISION: Final = "C06_EVENT_ID_COLLISION"
C06_STORE_IO_FAILURE: Final = "C06_STORE_IO_FAILURE"
C06_HUMAN_INPUT_INVALID: Final = "C06_HUMAN_INPUT_INVALID"

C06_ERROR_CODES: Final = (
    C06_CHAIN_PACKET_MISMATCH,
    C06_CHAIN_RUN_MISMATCH,
    C06_CHAIN_TIME_REGRESSION,
    C06_DECISION_TIME_BEFORE_RUN,
    C06_EVENT_ID_COLLISION,
    C06_HUMAN_INPUT_INVALID,
    C06_NONCANONICAL_C05_PACKET,
    C06_PACKET_BINDING_MISMATCH,
    C06_PREVIOUS_EVENT_MISMATCH,
    C06_REASON_CODE_OVERLAP,
    C06_REASON_CODE_UNKNOWN,
    C06_STORE_BUSY,
    C06_STORE_CORRUPT,
    C06_STORE_CYCLE,
    C06_STORE_DIRTY,
    C06_STORE_FORK,
    C06_STORE_IO_FAILURE,
    C06_STORE_ROOT_INVALID,
)


class C06Error(ValueError):
    """A stable fail-closed C06 validation or journal failure."""

    def __init__(self, code: str, state: str = "BLOCKED_CONTRACT") -> None:
        if code not in C06_ERROR_CODES:
            raise ValueError("unknown C06 error code")
        self.code = code
        self.state = state
        super().__init__(f"{state}: {code}")
