"""Closed W03-C01 decision-loop vocabularies. No transitions or policy live here."""

from enum import StrEnum


class UncertaintyStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ASSOCIATIVE_ONLY = "ASSOCIATIVE_ONLY"
    UNRESOLVED_DISPOSITION = "UNRESOLVED_DISPOSITION"


class ClaimType(StrEnum):
    FACT_CLAIM = "FACT_CLAIM"
    DERIVED_CLAIM = "DERIVED_CLAIM"
    ASSOCIATIVE_CLAIM = "ASSOCIATIVE_CLAIM"
    UNCERTAINTY_STATEMENT = "UNCERTAINTY_STATEMENT"


class TrustLevel(StrEnum):
    DIRECT_FACT = "DIRECT_FACT"
    DERIVED_FACT = "DERIVED_FACT"
    ASSOCIATIVE_EVIDENCE = "ASSOCIATIVE_EVIDENCE"
    UNKNOWN = "UNKNOWN"
    FORBIDDEN_INFERENCE = "FORBIDDEN_INFERENCE"


class FreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class SignalType(StrEnum):
    SUPPLIER_LATE_RECEIPT = "SUPPLIER_LATE_RECEIPT"
    MATERIAL_TIMING_RISK = "MATERIAL_TIMING_RISK"
    QUALITY_FAILURE = "QUALITY_FAILURE"
    REWORK_PRESENT = "REWORK_PRESENT"
    QUALITY_DISPOSITION_UNKNOWN = "QUALITY_DISPOSITION_UNKNOWN"
    QUEUE_DELAY = "QUEUE_DELAY"
    CAPACITY_PRESSURE = "CAPACITY_PRESSURE"
    DELIVERY_RISK = "DELIVERY_RISK"


class SignalState(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    UNKNOWN = "UNKNOWN"


class InterventionFamily(StrEnum):
    NO_ACTION = "NO_ACTION"
    SUPPLIER_INTERVENTION = "SUPPLIER_INTERVENTION"
    QUALITY_INTERVENTION = "QUALITY_INTERVENTION"
    CAPACITY_INTERVENTION = "CAPACITY_INTERVENTION"


class SimulationStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"


class RecommendationDisposition(StrEnum):
    CANDIDATE_RECOMMENDED = "CANDIDATE_RECOMMENDED"
    NO_ACTION = "NO_ACTION"
    NO_RECOMMENDATION = "NO_RECOMMENDATION"
    INVESTIGATION_ONLY = "INVESTIGATION_ONLY"
    DEFER_TO_HUMAN = "DEFER_TO_HUMAN"


class ExplanationMode(StrEnum):
    DETERMINISTIC_TEMPLATE = "DETERMINISTIC_TEMPLATE"
    BOUNDED_LLM = "BOUNDED_LLM"
    DEGRADED_TEMPLATE = "DEGRADED_TEMPLATE"


class HumanDecisionType(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    DEFER = "DEFER"


class EvaluationStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DecisionRunState(StrEnum):
    CREATED = "CREATED"
    SNAPSHOT_BUILDING = "SNAPSHOT_BUILDING"
    SNAPSHOT_READY = "SNAPSHOT_READY"
    TRUST_CHECKING = "TRUST_CHECKING"
    TRUST_VERIFIED = "TRUST_VERIFIED"
    SIGNALS_READY = "SIGNALS_READY"
    DIAGNOSIS_READY = "DIAGNOSIS_READY"
    CANDIDATES_READY = "CANDIDATES_READY"
    SIMULATION_READY = "SIMULATION_READY"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    PACKET_READY = "PACKET_READY"
    EXPLANATION_READY = "EXPLANATION_READY"
    HUMAN_PENDING = "HUMAN_PENDING"
    HUMAN_DECIDED = "HUMAN_DECIDED"
    RUNTIME_COMPLETE = "RUNTIME_COMPLETE"
    BLOCKED_CONTEXT = "BLOCKED_CONTEXT"
    BLOCKED_TEMPORAL = "BLOCKED_TEMPORAL"
    BLOCKED_HGT = "BLOCKED_HGT"
    BLOCKED_TRUST = "BLOCKED_TRUST"
    BLOCKED_CONTRACT = "BLOCKED_CONTRACT"
    BLOCKED_INSUFFICIENT_EVIDENCE = "BLOCKED_INSUFFICIENT_EVIDENCE"
    SIMULATION_PARTIAL = "SIMULATION_PARTIAL"
    SIMULATION_FAILED = "SIMULATION_FAILED"
    NO_RECOMMENDATION = "NO_RECOMMENDATION"
    EXPLANATION_DEGRADED = "EXPLANATION_DEGRADED"


class EvaluationState(StrEnum):
    EVAL_NOT_STARTED = "EVAL_NOT_STARTED"
    RECOMMENDATION_EVAL_READY = "RECOMMENDATION_EVAL_READY"
    RECOMMENDATION_EVALUATED = "RECOMMENDATION_EVALUATED"
    OUTCOME_PENDING = "OUTCOME_PENDING"
    OUTCOME_AVAILABLE = "OUTCOME_AVAILABLE"
    OUTCOME_EVALUATED = "OUTCOME_EVALUATED"
