"""Frozen, detail-free W04-C06 Human investigation policy."""

from __future__ import annotations

from typing import Final

HUMAN_INVESTIGATION_POLICY_VERSION: Final = "w04-c06-human-v1"
HUMAN_INVESTIGATION_STORE_VERSION: Final = "w04-c06-store-v1"
HUMAN_INVESTIGATION_WORKFLOW_VERSION: Final = "w04-c06-workflow-v1"
HUMAN_INVESTIGATION_PRODUCER: Final = "flowlens.investigation.c06_human"

C06_INVALID_REVIEW_CONTEXT: Final = "C06_INVALID_REVIEW_CONTEXT"
C06_HUMAN_INPUT_INVALID: Final = "C06_HUMAN_INPUT_INVALID"
C06_REVIEW_REFERENCE_MISMATCH: Final = "C06_REVIEW_REFERENCE_MISMATCH"
C06_OUTCOME_CONTRACT_MISMATCH: Final = "C06_OUTCOME_CONTRACT_MISMATCH"
C06_EVENT_MISMATCH: Final = "C06_EVENT_MISMATCH"
C06_PREVIOUS_EVENT_MISMATCH: Final = "C06_PREVIOUS_EVENT_MISMATCH"
C06_CHAIN_CASE_MISMATCH: Final = "C06_CHAIN_CASE_MISMATCH"
C06_CHAIN_TIME_REGRESSION: Final = "C06_CHAIN_TIME_REGRESSION"
C06_STORE_ROOT_INVALID: Final = "C06_STORE_ROOT_INVALID"
C06_STORE_BUSY: Final = "C06_STORE_BUSY"
C06_STORE_DIRTY: Final = "C06_STORE_DIRTY"
C06_STORE_CORRUPT: Final = "C06_STORE_CORRUPT"
C06_STORE_FORK: Final = "C06_STORE_FORK"
C06_STORE_CYCLE: Final = "C06_STORE_CYCLE"
C06_EVENT_ID_COLLISION: Final = "C06_EVENT_ID_COLLISION"
C06_STORE_IO_FAILURE: Final = "C06_STORE_IO_FAILURE"

C06_ERROR_CODES: Final = (
    C06_CHAIN_CASE_MISMATCH,
    C06_CHAIN_TIME_REGRESSION,
    C06_EVENT_ID_COLLISION,
    C06_EVENT_MISMATCH,
    C06_HUMAN_INPUT_INVALID,
    C06_INVALID_REVIEW_CONTEXT,
    C06_OUTCOME_CONTRACT_MISMATCH,
    C06_PREVIOUS_EVENT_MISMATCH,
    C06_REVIEW_REFERENCE_MISMATCH,
    C06_STORE_BUSY,
    C06_STORE_CORRUPT,
    C06_STORE_CYCLE,
    C06_STORE_DIRTY,
    C06_STORE_FORK,
    C06_STORE_IO_FAILURE,
    C06_STORE_ROOT_INVALID,
)


class C06HumanInvestigationError(ValueError):
    """One stable public code, without upstream or platform detail."""

    def __init__(self, code: str) -> None:
        if code not in C06_ERROR_CODES:
            raise ValueError("unknown C06 error code")
        self.code = code
        super().__init__(code)
