"""Closed W04-C01 structural vocabularies; these grant no execution authority."""

from enum import StrEnum


class FindingStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    UNRESOLVED = "UNRESOLVED"
    UNKNOWN = "UNKNOWN"


class ConflictType(StrEnum):
    DIRECT_VS_DIRECT = "DIRECT_VS_DIRECT"
    DIRECT_VS_DERIVED = "DIRECT_VS_DERIVED"
    TIMESTAMP_CONFLICT = "TIMESTAMP_CONFLICT"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    VALUE_CONFLICT = "VALUE_CONFLICT"


class UncertaintyType(StrEnum):
    UNKNOWN_EVIDENCE = "UNKNOWN_EVIDENCE"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    ASSOCIATIVE_ONLY = "ASSOCIATIVE_ONLY"
    FORBIDDEN_INFERENCE = "FORBIDDEN_INFERENCE"
    UNRESOLVED_QUESTION = "UNRESOLVED_QUESTION"


class HumanInvestigationOutcome(StrEnum):
    SUPPORTED_FINDING_RECORDED = "SUPPORTED_FINDING_RECORDED"
    NO_SUPPORTED_FINDING = "NO_SUPPORTED_FINDING"
    MORE_EVIDENCE_REQUIRED = "MORE_EVIDENCE_REQUIRED"
    DEFER = "DEFER"
    INVESTIGATION_REVIEW_COMPLETE = "INVESTIGATION_REVIEW_COMPLETE"


class SummaryRendererMode(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    BOUNDED_LLM = "BOUNDED_LLM"
    DEGRADED_FALLBACK = "DEGRADED_FALLBACK"
